# Test notebook

## Grocery products recognition

Hello and welcome to this notebook. 

This notebook trains a YOLOv2 algorithm in order to localize the grocery products in the supermarket shell.

The following dataset is used to train this CNN:
[Grocery Store dataset](https://www.amazon.de/clouddrive/share/J3OaZMNnhBpKG28mAfs5CqTgreQxFCY8uENGaIk7H3s?_encoding=UTF8&mgh=1&ref_=cd_ph_share_link_copy).

This dataset was annotated in the work by [George, Marian and Floerkemeier](http://vision.disi.unibo.it/index.php?option=com_content&view=article&id=111&catid=78). (There is only 76 images annotated.)

The Yolo (You Only Look Once) algorithm is presented in the following papers:
* Redmon et al., 2016 (https://arxiv.org/abs/1506.02640) 
* Redmon and Farhadi, 2016 (https://arxiv.org/abs/1612.08242).

The yolo algorithm was originally tested in [Darknet]( https://pjreddie.com/darknet). This algorithm has been implemented in python for several machine-learning frameworks. This work is based in the [YAD2K]( https://github.com/allanzelener/YAD2K) implementation for Keras and Tensorflow.

#### This notebook will guide you in order to test your own network


In [1]:
import colorsys
import imghdr
import os
import random

import numpy as np
import tensorflow as tf
from keras import backend as K
from keras.models import load_model
from keras.backend.tensorflow_backend import set_session
from PIL import Image, ImageDraw, ImageFont

from train_yolo_utils import draw

from yad2k.models.keras_yolo import yolo_head, yolo_boxes_to_corners, preprocess_true_boxes, yolo_loss, yolo_body, yolo_eval, tiny_yolo_body
from yad2k.utils.draw_boxes import draw_boxes


from yolo_utils import *

Using TensorFlow backend.


Because some problems with windowns 10, the test images are computed with the CPU

In [2]:
config = tf.ConfigProto(device_count = {'GPU': 0})
set_session(tf.Session(config=config))

In [3]:
# Paths of anchors and classes
anchors_path = 'model_data/yolo_anchors.txt'
classes_path = 'model_data/groceries_classes.txt'



#### Please put the images to test in a folder and add the path here

In [4]:
# Path where the test images are located
test_path    = 'images'
# Path where the test images will be located after the YOLO algorithm
output_path  = 'images/out'

In [5]:
# load the model
yolo_model = load_model('model_data/Products_recognition_body.h5')

C:\Program Files\Anaconda3\lib\site-packages\keras\models.py:251: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [6]:
# load the weights for the model
yolo_model.load_weights('model_data/trained_stage_3_best.h5')

In [7]:
# read classes and anchors
class_names = read_classes(classes_path)
anchors = read_anchors(anchors_path)

In [8]:
# get images paths
images_path=[]
for image_file in os.listdir(test_path):
    try:
        image_type = imghdr.what(os.path.join(test_path, image_file))
        if not image_type:
            continue
    except:
        continue
        
    images_path.append(test_path+'/'+image_file)

print(images_path)


['images/16.jpg', 'images/253.jpg', 'images/46.jpg', 'images/54.jpg', 'images/55.jpg']


In [9]:
# preprocess the images to the format of the yolo algorithm
processed_images, images = preprocess_images(images_path)

In [10]:
# Test the images
draw(yolo_model,
    class_names,
    anchors,
    processed_images,
    image_set='all', # assumes training/validation split is 0.9
    weights_name='model_data/trained_stage_3_best.h5',
    out_path="images/out",
    save_all=False)

(5, 1, 416, 416, 3)
Found 14 boxes for image.
[[  36.3269577   132.84387207  128.59158325  194.58450317]
 [ 227.73295593   76.09931946  312.1960144   137.14862061]
 [  43.55762482  199.31077576  131.93045044  261.74081421]
 [ 144.96020508  327.07556152  211.02326965  386.02005005]
 [  40.95552063  338.77905273  135.22770691  380.08422852]
 [ 233.10205078  169.49177551  315.68237305  238.97850037]
 [ 242.76408386  303.32897949  321.63592529  368.9102478 ]
 [ 320.47808838  171.26382446  390.99334717  250.06095886]
 [ 236.08024597  245.36761475  321.62112427  298.12075806]
 [ -14.97159767   -3.56864429  208.97059631   81.2219696 ]
 [  32.50404358   78.65345764  123.47944641  133.57655334]
 [ 202.59315491    8.41079903  339.61422729   65.44841766]
 [ 326.88937378   74.22484589  391.64422607  166.14689636]
 [ 323.07443237  272.48623657  398.87393188  337.66030884]]
(5, 1, 416, 416, 3)
product 0.70 (133, 36) (195, 129)
product 0.70 (76, 228) (137, 312)
product 0.67 (199, 44) (262, 132)
produ

# To see this images go to "images/out"